version: '3.9'
services:
  bombar:
    container_name: bombar
    image: bombar
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    volumes:
      - ../app:/usr/src/app
    env_file:
      - ../app/.env
    command: bash
    tty: true
